language: ruby
rvm:
  - 2.1
install: gem install jekyll -v 3.7.3 && gem install s3_website
script: jekyll build
after_success: 
  - bash postbuild.sh
  - s3_website push
notifications:
    slack: aiacc:DQJx1jxSipYMHzXBVtf4kMGH