---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _inductees
  label: Inductees
  create: documents
  match: "**/*"
  templates:
  - inductee
- type: jekyll-posts
  label: Press Releases
  create: all
- type: jekyll-pages
  label: Pages
  create: documents
  templates:
  - page-builder
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
